### ISSUE TITLE
warnings before installing

### ISSUE THREAD

**Issue by yosepito** [Klaus3d3/xDrip-Watchface#4]
I'm editing my self regarding issue #8: it is possible to save all the data and restore it. Read the new #8
----------x------------------------
Another tester here. Amazing the job you have made, @Klaus3d3 . I can contribute as a tester.

I will comment how I did and some warnings to avoid some mistakes for other testers.

What I did so far was:
1) install Huami Amazfit Tool from XDA (as already mentioned elsewhere by Klaus3d3: ([https://forum.xda-developers.com/smartwatch/amazfit/tool-huami-amazfit-tool-unlockadvanced-t3739828]). With that tool you needn't to do anything to your Pace/Stratos. As simple as installing that software, downloading the apks developed by Klaus3d3 and colleagues, and click on "install apk". Before that, you should check that the software detects your smartwatch (green in adb and in smartwatch detected). You should also click on "install drivers" so you will be sure that you have installed all what is needed.
2) Don't download/install the Klaus3d3's widget. As he said elsewhere, it's out of order. Download the watchface instead. You should also download the Klaus3d3's Xdrip version. It contains a specific menu to select features in the watchface and in the widget (also included in this watchface apk, so no need to install that other widget separately). 
3) connect your smartwatch to your computer by using the charger station/USB cable
4) in Huami Amazfit Tool-HAT, click on "install apk" and select the downloaded watchface apk (named as "app-debug.apk")
5) click on install, a ms-dos/command black screen will open. It may take a while and you will know it's done once it says "click a key to continue". Once you are done, within the same HAT you can click on "reboot" so your smartwatch will reboot
6) you will find 2 different features. One is the widget. If you scroll right and navigate the different apps installed, you will if the widget before the last one screen. That's the widget. If you long press your watchface, you could then navigate to the Xrdip watchface. That's amazing so you can see the usual info (steps, battery, temp) AND THE BG VALUES WITH AN ARROW.

7) You needn't to install Xdrip IN the smartwatch (something I was wondering). You just install the Klaus3d3's Xdrip version in your smartphone. There is no need to run Amazfit Watch companion app in the background of your smartphone to get the smartwatch connected to your Amazfit.

8) A WARNING: I had to uninstall the Jamorham's latest version of Xdrip. This means that you will loose your data and settings **unless you save your settings and back filled your data**. I had to **uninstall the original version of Xdrip** because, otherwise, I could not install the Klaus3d3's Xdrip version. To avoid losing your settings: (a) simply go to settings in your already version installed and go to load/save settings in your SD card. Select "save all your settings to your SD card". After installation, you can load it following the same procedure. (b) A second issue (_I was unable to solve yet)_**solved** is the issue of loosing all the history of data). WHAT YOU SHOULD DO before uninstalling your version is to backup your data to your Nightscout site, just in case. **You should also use the rightmost three dots to export your database, and use "import database" to restore it after you install the Klaus3d3 version.** _Anyway, I was unable to bring it back to my smartphone (maybe @Klaus3d3 or anyone may help with this??)._**SOLVED: do perform the procedure to export database before uninstalling Xdrip, then uninstall it and install the Klaus3d3 version; you won't loose anything because data is saved in a different folder to the app uninstalled.**

9) after you have saved your settings and backed-up your data **(exporting to SD), and just in case to your Nightscout site, [although you won't be able to restore your data from NS, just by importing from your SD following the 8.b procedure**], you can then uninstall your current version of Xdrip and install the Klaus3d3's version. 

10) voilá. After that, you will have to start the sensor (I had to do it), wait for initial calibrations, and the like. My recommendation is that you consider to install this at the moment you start a new sensor, so you won't lose your calibrations and the like.

Some improvements/minor bugs in this version of the smartwatch:

1. while the smartwatch is in sleep mode (not activated by double tapping...) there is an oriental character in the "month" number. Today is (weekday) Monday, (day) 19, (month) 11 and instead of the second "1" I see an oriental character. When double tapping to activate the smartwatch the right number appears, but on its right it continues to be that strange character.
2. When in sleep mode, I can see the current BG value and delta. However, it says "less than 10 minutes ago". I know it updates every 5 minutes following the Xdrip app, so my guess is that it is the problem of the idle mode of Amazfit (the same happened to me when using another watchface with the heart rate not updating properly). 
3. I can see the blue dots in the watchface. However, I don't know how to interpret them. I mean, I don't think I could interpret the slope or the like, despite I put the same 6-hour timeframe as in the smartphone. I don't mind really, since I can see the delta. Maybe it's a question of time to see a graph that I can interpret (only 20 dots so far). 
4. Neither I can see IOB, nor COB. this could be a great improvement
5. in the smartphone, I can see an error in the log related to "transport" -->failed transport service unconnected, but just after that log it appears the log saying that it was able to do that (I know it's the same BG because the timestamp is the same). Why is it unable to connect in first instance and the it can? A bug? SOLVED: i found that when double tapping any watchface and scrolling left/right to select Xdrip watchface, there was the possibility to click in "settings" (it was in Spanish, since my smartwatch is in that language); by clicking on that, you can simply change to some languages. In the Spanish version it reads now "Weekday"-->Lunes (Monday); Day -->19; Month-->ENERO (JANUARY), instead of the number plus the strange oriental character showed in the English version. It only changes that to my local language. It continues appearing in English other issues such as the words Steps, Battery-->Watch-->Phone, and the like. I really no need any additional translation for this, since the English version is shorter. It also translates the wording of "time since last reading", although not in idle mode ("less than 10 min ago" is the message by default). 

I will check battery consumption. Anyway, I deactivated the widget from the smartphone menu, since I see all that I want in the watchface. Thanks to all of you for doing this possible. I will also check the Sports mode since I ride my road bike and use this to hear how well I'm while biking.
thanks!

**Additional discovery: the blue dots are converted in orange dots if above the upper BG limits, and in red if below. Additionally, the place where one can read the info of BGs and trends shifts to a read background colour if the BG is above the upper limits. In addition, I can snooze the smartphone alarms with the smartwatch. Thank you very much to all of you: this is an amazing way of improving our life!!. Big thanks!!**

**Comment by Klaus3d3** [comment]
Thanks for this tutorial.

In fact, the graph on the watchface is actually a bitmap wich is created on the phone and then sent to the watch. The colors for the dots are the same as in the app. So if there is a color wich is hard to see on the watch due to its display type, just change the colors in the display settings if xdrip+.
For example, yellow is very hard to see on the standby display.

to No. 7. You always need the amazfit watch app running in the background. xdrip+ crashes otherwise. 
But honestly, i don't think that anybody uses the watch without the app. ;-)
